### ISSUE TITLE
SIGNUP BUTTON UI CHANGE

### ISSUE THREAD

**Issue by biswajit035** [Fem-STEM/FemSTEM-Web-App#14]
It will look better if LOGIN button and **SIGNUP button look** same. Here **border radius should change** a little bit to look SIGNUP button as LOGIN button
![Screenshot (27)](https://user-images.githubusercontent.com/88304589/156694671-5d95b4d4-31ca-41df-8352-5d663d08e7cc.png)

**Comment by biswajit035** [comment]
I would like to work on it

**Comment by Swatilekha-Roy** [comment]
Go ahead, @BiswjitDebnath! All the best.

- Please make sure you refer to the issue number # when you are making a pull request.
- Please add screenshots and (or) screen recordings for your resolution of the issue in your pull request, in order to ensure your pr gets merged soon. This is highly recommended.
